###NAMA : FARISYAH LUTFIAH HANIS
###ID   : DS5H17

#Import File dari Google Drive

In [ ]:
from google.colab import drive

In [ ]:
drive.mount ('/content/drive')

Mounted at /content/drive

In [ ]:
# import library
import pandas as pd

In [ ]:
# /content/drive/My Drive/nama folder/nama file
df_h = pd.read_excel(r'/content/drive/My Drive/Dataset/Dataset_Assignment.xlsx')

In [ ]:
display(pd.DataFrame(df_h))

,nomor_peserta,nama,jurusan,berat_badan,tinggi_badan
0,DS5H01,Irfan Muhammad,Geofisika,85,159
1,DS5H02,Rofik,Teknik Informatika,48,160
2,DS5H03,Saeful Ismail,Fisika,48,157
3,DS5H04,Hibban Daffa Ramadhan,Sistem Informasi,55,168
4,DS5H05,Nida Atus Sa'adah,Matematika,54,153
5,DS5H06,Gustian,Statistika Terapan dan Komputasi,58,168
6,DS5H07,Shaffira Dien Auliya,Teknik Informatika,57,160
7,DS5H08,Dandi Dwi Darmawan,Teknik Informatika,50,169
8,DS5H09,Nabila Rizky Amalia Putri,Sains Data,44,158
9,DS5H10,Adliyan Rizky Pratama,Teknik Informatika,74,171
10,DS5H11,Muhimin,Manajemen,78,170
11,DS5H12,Zahra Putri Azizah,Sistem Informasi,53,158
12,DS5H13,Silverius Rinovicto Adi Prasetyo,Geofisika,65,162
13,DS5H14,Akwila Mordekhai Prasetyo,Psikologi,60,170
14,DS5H15,Nur Azizah,Sistem informasi,54,158
15,DS5H16,Syafala Shasi Arthana,Manajemen,41,150
16,DS5H17,Farisyah Lutfiah Hanis,Sistem Informasi,52,165
17,DS5H18,Siti Salwa Nurhadiva,Teknik Telekomunikasi,54,163
18,DS5H19,Muslim Musthofa Febri,Perpustakaan,55,160
19,DS5H20,Muhammad Aditya Adinugraha,Teknik Biomedis,90,173
20,DS5H21,Pernanda Surbakti,Teknik Informatika,76,174
21,DS5H22,Alicia Alfia Asokawati,Teknologi Informasi,72,171
22,DS5H23,Yusuf Gustri Alfari,Teknik industri,65,168
23,DS5H24,Gita Wahyu Romadhon Putra,Manajemen Bisnis,58,170

# 1. Identifikasi Data

In [ ]:
#Tipe Data
tipe_data = df_h.dtypes
tipe_data

nomor_peserta    object
nama             object
jurusan          object
berat_badan       int64
tinggi_badan      int64
dtype: object

In [ ]:
#Jumlah kolom dan baris
jumlah_kolom, jumlah_baris = df_h.shape
jumlah_kolom, jumlah_baris

(24, 5)

In [ ]:
#Melihat info data
df_h.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   nomor_peserta  24 non-null     object
 1   nama           24 non-null     object
 2   jurusan        24 non-null     object
 3   berat_badan    24 non-null     int64
 4   tinggi_badan   24 non-null     int64
dtypes: int64(2), object(3)
memory usage: 1.1+ KB

# 2. Hitung BMI

In [ ]:
# Mengubah tinggi badan cm ke meter
df_h['tinggi_badan_m'] = df_h['tinggi_badan'] / 100
df_h

# Hitung BMI, membulatkannya, dan update df_h
df_h['BMI'] = round(df_h['berat_badan'] / (df_h['tinggi_badan_m'] ** 2), 1)
df_h

,nomor_peserta,nama,jurusan,berat_badan,tinggi_badan,tinggi_badan_m,BMI
0,DS5H01,Irfan Muhammad,Geofisika,85,159,1.59,33.6
1,DS5H02,Rofik,Teknik Informatika,48,160,1.60,18.7
2,DS5H03,Saeful Ismail,Fisika,48,157,1.57,19.5
3,DS5H04,Hibban Daffa Ramadhan,Sistem Informasi,55,168,1.68,19.5
4,DS5H05,Nida Atus Sa'adah,Matematika,54,153,1.53,23.1
5,DS5H06,Gustian,Statistika Terapan dan Komputasi,58,168,1.68,20.5
6,DS5H07,Shaffira Dien Auliya,Teknik Informatika,57,160,1.60,22.3
7,DS5H08,Dandi Dwi Darmawan,Teknik Informatika,50,169,1.69,17.5
8,DS5H09,Nabila Rizky Amalia Putri,Sains Data,44,158,1.58,17.6
9,DS5H10,Adliyan Rizky Pratama,Teknik Informatika,74,171,1.71,25.3
10,DS5H11,Muhimin,Manajemen,78,170,1.70,27.0
11,DS5H12,Zahra Putri Azizah,Sistem Informasi,53,158,1.58,21.2
12,DS5H13,Silverius Rinovicto Adi Prasetyo,Geofisika,65,162,1.62,24.8
13,DS5H14,Akwila Mordekhai Prasetyo,Psikologi,60,170,1.70,20.8
14,DS5H15,Nur Azizah,Sistem informasi,54,158,1.58,21.6
15,DS5H16,Syafala Shasi Arthana,Manajemen,41,150,1.50,18.2
16,DS5H17,Farisyah Lutfiah Hanis,Sistem Informasi,52,165,1.65,19.1
17,DS5H18,Siti Salwa Nurhadiva,Teknik Telekomunikasi,54,163,1.63,20.3
18,DS5H19,Muslim Musthofa Febri,Perpustakaan,55,160,1.60,21.5
19,DS5H20,Muhammad Aditya Adinugraha,Teknik Biomedis,90,173,1.73,30.1
20,DS5H21,Pernanda Surbakti,Teknik Informatika,76,174,1.74,25.1
21,DS5H22,Alicia Alfia Asokawati,Teknologi Informasi,72,171,1.71,24.6
22,DS5H23,Yusuf Gustri Alfari,Teknik industri,65,168,1.68,23.0
23,DS5H24,Gita Wahyu Romadhon Putra,Manajemen Bisnis,58,170,1.70,20.1

# 3. Membuat program hitung BMI

In [ ]:
# Fungsi untuk menghitung BMI
def hitung_bmi(berat, tinggi):
    bmi = berat / (tinggi ** 2)
    return bmi

# Input berat badan (kg) dan tinggi badan (m)
berat = float(input("Masukkan berat badan Anda (kg): "))
tinggi = float(input("Masukkan tinggi badan Anda (m): "))

# Hitung BMI
bmi = hitung_bmi(berat, tinggi)

# Menampilkan hasil BMI
print("Indeks Massa Tubuh (BMI) Anda adalah:", round(bmi, 1))

Masukkan berat badan Anda (kg): 65
Masukkan tinggi badan Anda (m): 1.55
Indeks Massa Tubuh (BMI) Anda adalah: 27.1

# 4. Update dataframe menambahkan hasil BMI

In [ ]:
# data sudah terupdate di nomor sebelumnya
df_h

,nomor_peserta,nama,jurusan,berat_badan,tinggi_badan,tinggi_badan_m,BMI
0,DS5H01,Irfan Muhammad,Geofisika,85,159,1.59,33.6
1,DS5H02,Rofik,Teknik Informatika,48,160,1.60,18.7
2,DS5H03,Saeful Ismail,Fisika,48,157,1.57,19.5
3,DS5H04,Hibban Daffa Ramadhan,Sistem Informasi,55,168,1.68,19.5
4,DS5H05,Nida Atus Sa'adah,Matematika,54,153,1.53,23.1
5,DS5H06,Gustian,Statistika Terapan dan Komputasi,58,168,1.68,20.5
6,DS5H07,Shaffira Dien Auliya,Teknik Informatika,57,160,1.60,22.3
7,DS5H08,Dandi Dwi Darmawan,Teknik Informatika,50,169,1.69,17.5
8,DS5H09,Nabila Rizky Amalia Putri,Sains Data,44,158,1.58,17.6
9,DS5H10,Adliyan Rizky Pratama,Teknik Informatika,74,171,1.71,25.3
10,DS5H11,Muhimin,Manajemen,78,170,1.70,27.0
11,DS5H12,Zahra Putri Azizah,Sistem Informasi,53,158,1.58,21.2
12,DS5H13,Silverius Rinovicto Adi Prasetyo,Geofisika,65,162,1.62,24.8
13,DS5H14,Akwila Mordekhai Prasetyo,Psikologi,60,170,1.70,20.8
14,DS5H15,Nur Azizah,Sistem informasi,54,158,1.58,21.6
15,DS5H16,Syafala Shasi Arthana,Manajemen,41,150,1.50,18.2
16,DS5H17,Farisyah Lutfiah Hanis,Sistem Informasi,52,165,1.65,19.1
17,DS5H18,Siti Salwa Nurhadiva,Teknik Telekomunikasi,54,163,1.63,20.3
18,DS5H19,Muslim Musthofa Febri,Perpustakaan,55,160,1.60,21.5
19,DS5H20,Muhammad Aditya Adinugraha,Teknik Biomedis,90,173,1.73,30.1
20,DS5H21,Pernanda Surbakti,Teknik Informatika,76,174,1.74,25.1
21,DS5H22,Alicia Alfia Asokawati,Teknologi Informasi,72,171,1.71,24.6
22,DS5H23,Yusuf Gustri Alfari,Teknik industri,65,168,1.68,23.0
23,DS5H24,Gita Wahyu Romadhon Putra,Manajemen Bisnis,58,170,1.70,20.1

# 5.  Status BMI

In [ ]:
# Membuat kolom baru 'Status BMI' berdasarkan kategori BMI
df_h['status_BMI'] = pd.cut(df_h['BMI'], bins=[0, 18.5, 24.9, 29.9, float('inf')],
                         labels=['Underweight', 'Normal', 'Overweight', 'Obesity'], right=True)

# Menampilkan DataFrame dengan kolom 'Status BMI'
df_h

,nomor_peserta,nama,jurusan,berat_badan,tinggi_badan,tinggi_badan_m,BMI,status_BMI
0,DS5H01,Irfan Muhammad,Geofisika,85,159,1.59,33.6,Obesity
1,DS5H02,Rofik,Teknik Informatika,48,160,1.60,18.7,Normal
2,DS5H03,Saeful Ismail,Fisika,48,157,1.57,19.5,Normal
3,DS5H04,Hibban Daffa Ramadhan,Sistem Informasi,55,168,1.68,19.5,Normal
4,DS5H05,Nida Atus Sa'adah,Matematika,54,153,1.53,23.1,Normal
5,DS5H06,Gustian,Statistika Terapan dan Komputasi,58,168,1.68,20.5,Normal
6,DS5H07,Shaffira Dien Auliya,Teknik Informatika,57,160,1.60,22.3,Normal
7,DS5H08,Dandi Dwi Darmawan,Teknik Informatika,50,169,1.69,17.5,Underweight
8,DS5H09,Nabila Rizky Amalia Putri,Sains Data,44,158,1.58,17.6,Underweight
9,DS5H10,Adliyan Rizky Pratama,Teknik Informatika,74,171,1.71,25.3,Overweight
10,DS5H11,Muhimin,Manajemen,78,170,1.70,27.0,Overweight
11,DS5H12,Zahra Putri Azizah,Sistem Informasi,53,158,1.58,21.2,Normal
12,DS5H13,Silverius Rinovicto Adi Prasetyo,Geofisika,65,162,1.62,24.8,Normal
13,DS5H14,Akwila Mordekhai Prasetyo,Psikologi,60,170,1.70,20.8,Normal
14,DS5H15,Nur Azizah,Sistem informasi,54,158,1.58,21.6,Normal
15,DS5H16,Syafala Shasi Arthana,Manajemen,41,150,1.50,18.2,Underweight
16,DS5H17,Farisyah Lutfiah Hanis,Sistem Informasi,52,165,1.65,19.1,Normal
17,DS5H18,Siti Salwa Nurhadiva,Teknik Telekomunikasi,54,163,1.63,20.3,Normal
18,DS5H19,Muslim Musthofa Febri,Perpustakaan,55,160,1.60,21.5,Normal
19,DS5H20,Muhammad Aditya Adinugraha,Teknik Biomedis,90,173,1.73,30.1,Obesity
20,DS5H21,Pernanda Surbakti,Teknik Informatika,76,174,1.74,25.1,Overweight
21,DS5H22,Alicia Alfia Asokawati,Teknologi Informasi,72,171,1.71,24.6,Normal
22,DS5H23,Yusuf Gustri Alfari,Teknik industri,65,168,1.68,23.0,Normal
23,DS5H24,Gita Wahyu Romadhon Putra,Manajemen Bisnis,58,170,1.70,20.1,Normal

# 6. Mengurutkan Data

## a. Berdasarkan tinggi badan dari yang tertinggi ke rendah

In [ ]:
df_h_sorted = df_h.sort_values(by='tinggi_badan_m', ascending=False)
print(df_h_sorted)

   nomor_peserta                              nama  \
20        DS5H21                 Pernanda Surbakti
19        DS5H20        Muhammad Aditya Adinugraha
21        DS5H22            Alicia Alfia Asokawati
9         DS5H10             Adliyan Rizky Pratama
23        DS5H24         Gita Wahyu Romadhon Putra
13        DS5H14         Akwila Mordekhai Prasetyo
10        DS5H11                           Muhimin
7         DS5H08                Dandi Dwi Darmawan
22        DS5H23               Yusuf Gustri Alfari
3         DS5H04             Hibban Daffa Ramadhan
5         DS5H06                           Gustian
16        DS5H17            Farisyah Lutfiah Hanis
17        DS5H18              Siti Salwa Nurhadiva
12        DS5H13  Silverius Rinovicto Adi Prasetyo
1         DS5H02                             Rofik
18        DS5H19             Muslim Musthofa Febri
6         DS5H07              Shaffira Dien Auliya
0         DS5H01                    Irfan Muhammad
14        DS5H15                        Nur Azizah
11        DS5H12                Zahra Putri Azizah
8         DS5H09         Nabila Rizky Amalia Putri
2         DS5H03                     Saeful Ismail
4         DS5H05                 Nida Atus Sa'adah
15        DS5H16             Syafala Shasi Arthana

                             jurusan  berat_badan  tinggi_badan  \
20                Teknik Informatika           76           174
19                   Teknik Biomedis           90           173
21               Teknologi Informasi           72           171
9                 Teknik Informatika           74           171
23                  Manajemen Bisnis           58           170
13                         Psikologi           60           170
10                         Manajemen           78           170
7                 Teknik Informatika           50           169
22                   Teknik industri           65           168
3                   Sistem Informasi           55           168
5   Statistika Terapan dan Komputasi           58           168
16                  Sistem Informasi           52           165
17             Teknik Telekomunikasi           54           163
12                         Geofisika           65           162
1                 Teknik Informatika           48           160
18                      Perpustakaan           55           160
6                 Teknik Informatika           57           160
0                          Geofisika           85           159
14                  Sistem informasi           54           158
11                  Sistem Informasi           53           158
8                         Sains Data           44           158
2                             Fisika           48           157
4                         Matematika           54           153
15                         Manajemen           41           150

    tinggi_badan_m   BMI   status_BMI
20            1.74  25.1   Overweight
19            1.73  30.1      Obesity
21            1.71  24.6       Normal
9             1.71  25.3   Overweight
23            1.70  20.1       Normal
13            1.70  20.8       Normal
10            1.70  27.0   Overweight
7             1.69  17.5  Underweight
22            1.68  23.0       Normal
3             1.68  19.5       Normal
5             1.68  20.5       Normal
16            1.65  19.1       Normal
17            1.63  20.3       Normal
12            1.62  24.8       Normal
1             1.60  18.7       Normal
18            1.60  21.5       Normal
6             1.60  22.3       Normal
0             1.59  33.6      Obesity
14            1.58  21.6       Normal
11            1.58  21.2       Normal
8             1.58  17.6  Underweight
2             1.57  19.5       Normal
4             1.53  23.1       Normal
15            1.50  18.2  Underweight

## b. Berdasarkan nama dari Z-A

In [ ]:
df_h_sorted = df_h.sort_values(by='nama', ascending=False)
print(df_h_sorted)

   nomor_peserta                              nama  \
11        DS5H12                Zahra Putri Azizah
22        DS5H23               Yusuf Gustri Alfari
15        DS5H16             Syafala Shasi Arthana
17        DS5H18              Siti Salwa Nurhadiva
12        DS5H13  Silverius Rinovicto Adi Prasetyo
6         DS5H07              Shaffira Dien Auliya
2         DS5H03                     Saeful Ismail
1         DS5H02                             Rofik
20        DS5H21                 Pernanda Surbakti
14        DS5H15                        Nur Azizah
4         DS5H05                 Nida Atus Sa'adah
8         DS5H09         Nabila Rizky Amalia Putri
18        DS5H19             Muslim Musthofa Febri
10        DS5H11                           Muhimin
19        DS5H20        Muhammad Aditya Adinugraha
0         DS5H01                    Irfan Muhammad
3         DS5H04             Hibban Daffa Ramadhan
5         DS5H06                           Gustian
23        DS5H24         Gita Wahyu Romadhon Putra
16        DS5H17            Farisyah Lutfiah Hanis
7         DS5H08                Dandi Dwi Darmawan
21        DS5H22            Alicia Alfia Asokawati
13        DS5H14         Akwila Mordekhai Prasetyo
9         DS5H10             Adliyan Rizky Pratama

                             jurusan  berat_badan  tinggi_badan  \
11                  Sistem Informasi           53           158
22                   Teknik industri           65           168
15                         Manajemen           41           150
17             Teknik Telekomunikasi           54           163
12                         Geofisika           65           162
6                 Teknik Informatika           57           160
2                             Fisika           48           157
1                 Teknik Informatika           48           160
20                Teknik Informatika           76           174
14                  Sistem informasi           54           158
4                         Matematika           54           153
8                         Sains Data           44           158
18                      Perpustakaan           55           160
10                         Manajemen           78           170
19                   Teknik Biomedis           90           173
0                          Geofisika           85           159
3                   Sistem Informasi           55           168
5   Statistika Terapan dan Komputasi           58           168
23                  Manajemen Bisnis           58           170
16                  Sistem Informasi           52           165
7                 Teknik Informatika           50           169
21               Teknologi Informasi           72           171
13                         Psikologi           60           170
9                 Teknik Informatika           74           171

    tinggi_badan_m   BMI   status_BMI
11            1.58  21.2       Normal
22            1.68  23.0       Normal
15            1.50  18.2  Underweight
17            1.63  20.3       Normal
12            1.62  24.8       Normal
6             1.60  22.3       Normal
2             1.57  19.5       Normal
1             1.60  18.7       Normal
20            1.74  25.1   Overweight
14            1.58  21.6       Normal
4             1.53  23.1       Normal
8             1.58  17.6  Underweight
18            1.60  21.5       Normal
10            1.70  27.0   Overweight
19            1.73  30.1      Obesity
0             1.59  33.6      Obesity
3             1.68  19.5       Normal
5             1.68  20.5       Normal
23            1.70  20.1       Normal
16            1.65  19.1       Normal
7             1.69  17.5  Underweight
21            1.71  24.6       Normal
13            1.70  20.8       Normal
9             1.71  25.3   Overweight

#7. Filter dataframe df

## a. Status BMI diluar normal

In [ ]:
filtered_no_normal = df_h[df_h['status_BMI'] != 'Normal']
print(filtered_no_normal)

   nomor_peserta                        nama             jurusan  berat_badan  \
0         DS5H01              Irfan Muhammad           Geofisika           85
7         DS5H08          Dandi Dwi Darmawan  Teknik Informatika           50
8         DS5H09   Nabila Rizky Amalia Putri          Sains Data           44
9         DS5H10       Adliyan Rizky Pratama  Teknik Informatika           74
10        DS5H11                     Muhimin           Manajemen           78
15        DS5H16       Syafala Shasi Arthana           Manajemen           41
19        DS5H20  Muhammad Aditya Adinugraha     Teknik Biomedis           90
20        DS5H21           Pernanda Surbakti  Teknik Informatika           76

    tinggi_badan  tinggi_badan_m   BMI   status_BMI
0            159            1.59  33.6      Obesity
7            169            1.69  17.5  Underweight
8            158            1.58  17.6  Underweight
9            171            1.71  25.3   Overweight
10           170            1.70  27.0   Overweight
15           150            1.50  18.2  Underweight
19           173            1.73  30.1      Obesity
20           174            1.74  25.1   Overweight

## b. Tinggi Badan > 169 cm dan Berat Badan > 60 kg

In [ ]:
filtered_tb_bb = df_h[(df_h['tinggi_badan'] > 169) & (df_h['berat_badan'] > 60)]
print(filtered_tb_bb)

   nomor_peserta                        nama              jurusan  \
9         DS5H10       Adliyan Rizky Pratama   Teknik Informatika
10        DS5H11                     Muhimin            Manajemen
19        DS5H20  Muhammad Aditya Adinugraha      Teknik Biomedis
20        DS5H21           Pernanda Surbakti   Teknik Informatika
21        DS5H22      Alicia Alfia Asokawati  Teknologi Informasi

    berat_badan  tinggi_badan  tinggi_badan_m   BMI  status_BMI
9            74           171            1.71  25.3  Overweight
10           78           170            1.70  27.0  Overweight
19           90           173            1.73  30.1     Obesity
20           76           174            1.74  25.1  Overweight
21           72           171            1.71  24.6      Normal

## c. Nama yang mengandung huruf “y”

In [ ]:
filtered_y = df_h[df_h['nama'].str.contains('y', case=False)]
print(filtered_y)

   nomor_peserta                              nama             jurusan  \
6         DS5H07              Shaffira Dien Auliya  Teknik Informatika
8         DS5H09         Nabila Rizky Amalia Putri          Sains Data
9         DS5H10             Adliyan Rizky Pratama  Teknik Informatika
12        DS5H13  Silverius Rinovicto Adi Prasetyo           Geofisika
13        DS5H14         Akwila Mordekhai Prasetyo           Psikologi
15        DS5H16             Syafala Shasi Arthana           Manajemen
16        DS5H17            Farisyah Lutfiah Hanis    Sistem Informasi
19        DS5H20        Muhammad Aditya Adinugraha     Teknik Biomedis
22        DS5H23               Yusuf Gustri Alfari     Teknik industri
23        DS5H24         Gita Wahyu Romadhon Putra    Manajemen Bisnis

    berat_badan  tinggi_badan  tinggi_badan_m   BMI   status_BMI
6            57           160            1.60  22.3       Normal
8            44           158            1.58  17.6  Underweight
9            74           171            1.71  25.3   Overweight
12           65           162            1.62  24.8       Normal
13           60           170            1.70  20.8       Normal
15           41           150            1.50  18.2  Underweight
16           52           165            1.65  19.1       Normal
19           90           173            1.73  30.1      Obesity
22           65           168            1.68  23.0       Normal
23           58           170            1.70  20.1       Normal

## d. Siapa saja yang berat badannya kurang dari 60 kg

In [ ]:
filtered_bb = df_h[(df_h['berat_badan'] < 60)]
print(filtered_bb)

   nomor_peserta                       nama                           jurusan  \
1         DS5H02                      Rofik                Teknik Informatika
2         DS5H03              Saeful Ismail                            Fisika
3         DS5H04      Hibban Daffa Ramadhan                  Sistem Informasi
4         DS5H05          Nida Atus Sa'adah                        Matematika
5         DS5H06                    Gustian  Statistika Terapan dan Komputasi
6         DS5H07       Shaffira Dien Auliya                Teknik Informatika
7         DS5H08         Dandi Dwi Darmawan                Teknik Informatika
8         DS5H09  Nabila Rizky Amalia Putri                        Sains Data
11        DS5H12         Zahra Putri Azizah                  Sistem Informasi
14        DS5H15                 Nur Azizah                  Sistem informasi
15        DS5H16      Syafala Shasi Arthana                         Manajemen
16        DS5H17     Farisyah Lutfiah Hanis                  Sistem Informasi
17        DS5H18       Siti Salwa Nurhadiva             Teknik Telekomunikasi
18        DS5H19      Muslim Musthofa Febri                      Perpustakaan
23        DS5H24  Gita Wahyu Romadhon Putra                  Manajemen Bisnis

    berat_badan  tinggi_badan  tinggi_badan_m   BMI   status_BMI
1            48           160            1.60  18.7       Normal
2            48           157            1.57  19.5       Normal
3            55           168            1.68  19.5       Normal
4            54           153            1.53  23.1       Normal
5            58           168            1.68  20.5       Normal
6            57           160            1.60  22.3       Normal
7            50           169            1.69  17.5  Underweight
8            44           158            1.58  17.6  Underweight
11           53           158            1.58  21.2       Normal
14           54           158            1.58  21.6       Normal
15           41           150            1.50  18.2  Underweight
16           52           165            1.65  19.1       Normal
17           54           163            1.63  20.3       Normal
18           55           160            1.60  21.5       Normal
23           58           170            1.70  20.1       Normal

# 8. Tambahkan nomor urut pada dataframe

In [ ]:
# Menambahkan kolom 'No.' dengan nomor urut sebagai kolom pertama
df_h.insert(0, 'No.', range(1, len(df_h) + 1))

# Menampilkan DataFrame yang telah diperbarui
print(df_h)

    No. nomor_peserta                              nama  \
0     1        DS5H01                    Irfan Muhammad
1     2        DS5H02                             Rofik
2     3        DS5H03                     Saeful Ismail
3     4        DS5H04             Hibban Daffa Ramadhan
4     5        DS5H05                 Nida Atus Sa'adah
5     6        DS5H06                           Gustian
6     7        DS5H07              Shaffira Dien Auliya
7     8        DS5H08                Dandi Dwi Darmawan
8     9        DS5H09         Nabila Rizky Amalia Putri
9    10        DS5H10             Adliyan Rizky Pratama
10   11        DS5H11                           Muhimin
11   12        DS5H12                Zahra Putri Azizah
12   13        DS5H13  Silverius Rinovicto Adi Prasetyo
13   14        DS5H14         Akwila Mordekhai Prasetyo
14   15        DS5H15                        Nur Azizah
15   16        DS5H16             Syafala Shasi Arthana
16   17        DS5H17            Farisyah Lutfiah Hanis
17   18        DS5H18              Siti Salwa Nurhadiva
18   19        DS5H19             Muslim Musthofa Febri
19   20        DS5H20        Muhammad Aditya Adinugraha
20   21        DS5H21                 Pernanda Surbakti
21   22        DS5H22            Alicia Alfia Asokawati
22   23        DS5H23               Yusuf Gustri Alfari
23   24        DS5H24         Gita Wahyu Romadhon Putra

                             jurusan  berat_badan  tinggi_badan  \
0                          Geofisika           85           159
1                 Teknik Informatika           48           160
2                             Fisika           48           157
3                   Sistem Informasi           55           168
4                         Matematika           54           153
5   Statistika Terapan dan Komputasi           58           168
6                 Teknik Informatika           57           160
7                 Teknik Informatika           50           169
8                         Sains Data           44           158
9                 Teknik Informatika           74           171
10                         Manajemen           78           170
11                  Sistem Informasi           53           158
12                         Geofisika           65           162
13                         Psikologi           60           170
14                  Sistem informasi           54           158
15                         Manajemen           41           150
16                  Sistem Informasi           52           165
17             Teknik Telekomunikasi           54           163
18                      Perpustakaan           55           160
19                   Teknik Biomedis           90           173
20                Teknik Informatika           76           174
21               Teknologi Informasi           72           171
22                   Teknik industri           65           168
23                  Manajemen Bisnis           58           170

    tinggi_badan_m   BMI   status_BMI
0             1.59  33.6      Obesity
1             1.60  18.7       Normal
2             1.57  19.5       Normal
3             1.68  19.5       Normal
4             1.53  23.1       Normal
5             1.68  20.5       Normal
6             1.60  22.3       Normal
7             1.69  17.5  Underweight
8             1.58  17.6  Underweight
9             1.71  25.3   Overweight
10            1.70  27.0   Overweight
11            1.58  21.2       Normal
12            1.62  24.8       Normal
13            1.70  20.8       Normal
14            1.58  21.6       Normal
15            1.50  18.2  Underweight
16            1.65  19.1       Normal
17            1.63  20.3       Normal
18            1.60  21.5       Normal
19            1.73  30.1      Obesity
20            1.74  25.1   Overweight
21            1.71  24.6       Normal
22            1.68  23.0       Normal
23            1.70  20.1       Normal

# 9. Cari nilai-nilai berikut:

## Kelompokkan tinggi badan dan berat badan serta cari nilai terendah dan tertingginya

In [ ]:
# Kelompokkan berat badan dan tinggi badan
berat_kelompok = pd.cut(df_h['berat_badan'], bins=[0, 50, 60, 70, 80, float('inf')],
                        labels=['<50', '50-60', '60-70', '70-80', '>80'])
tinggi_kelompok = pd.cut(df_h['tinggi_badan'], bins=[0, 160, 170, 180, 190, float('inf')],
                         labels=['<160', '160-170', '170-180', '180-190', '>190'])

# Temukan nilai terendah dan tertinggi
berat_terendah = df_h['berat_badan'].min()
berat_tertinggi = df_h['berat_badan'].max()
tinggi_terendah = df_h['tinggi_badan'].min()
tinggi_tertinggi = df_h['tinggi_badan'].max()

print("Kelompok Berat Badan:")
print(berat_kelompok.value_counts())
print("\nKelompok Tinggi Badan:")
print(tinggi_kelompok.value_counts())
print("\nBerat Badan Terendah:", berat_terendah)
print("Berat Badan Tertinggi:", berat_tertinggi)
print("Tinggi Badan Terendah:", tinggi_terendah)
print("Tinggi Badan Tertinggi:", tinggi_tertinggi)

Kelompok Berat Badan:
50-60    11
<50       5
70-80     4
60-70     2
>80       2
Name: berat_badan, dtype: int64

Kelompok Tinggi Badan:
<160       10
160-170    10
170-180     4
180-190     0
>190        0
Name: tinggi_badan, dtype: int64

Berat Badan Terendah: 41
Berat Badan Tertinggi: 90
Tinggi Badan Terendah: 150
Tinggi Badan Tertinggi: 174

## Berapa nilai rata-rata tinggi badan siswa?

In [ ]:
# Menghitung rata-rata tinggi badan siswa
rata_rata_tinggi = df_h['tinggi_badan'].mean()
rata_rata_tinggi = round(rata_rata_tinggi, 1)

print("Rata-rata tinggi badan siswa:", rata_rata_tinggi, "cm")

Rata-rata tinggi badan siswa: 164.0 cm

## Berapa rata-rata berat badan siswa?

In [ ]:
# Menghitung rata-rata berat badan siswa
rata_rata_berat = df_h['berat_badan'].mean()
rata_rata_berat = round(rata_rata_berat, 1)

print("Rata-rata berat badan siswa:", rata_rata_berat, "kg")

Rata-rata berat badan siswa: 60.2 kg

## Ada berapa orang jumlah siswa  yang tercatat pada dataframe df?

In [ ]:
# Menghitung jumlah siswa
jumlah_siswa = df_h.shape[0]

print("Jumlah siswa:", jumlah_siswa)

Jumlah siswa: 24

## 5 orang dengan nilai BMI tertinggi

In [ ]:
# Mengurutkan DataFrame berdasarkan nilai BMI tertinggi
df_sorted = df_h.sort_values(by='BMI', ascending=False)

# Mengambil 5 orang dengan nilai BMI tertinggi
top_5 = df_sorted.head(5)

# Menampilkan hasil
print("5 orang dengan nilai BMI tertinggi:")
print(top_5[['nama', 'BMI']])

5 orang dengan nilai BMI tertinggi:
                          nama   BMI
0               Irfan Muhammad  33.6
19  Muhammad Aditya Adinugraha  30.1
10                     Muhimin  27.0
9        Adliyan Rizky Pratama  25.3
20           Pernanda Surbakti  25.1

## Ada berapa orang yang tergolong status Underweight, Normal, Overweight, dan Obesity?

In [ ]:
# Menghitung jumlah orang dalam setiap kategori BMI
jumlah_underweight = (df_h['status_BMI'] == 'Underweight').sum()
jumlah_normal = (df_h['status_BMI'] == 'Normal').sum()
jumlah_overweight = (df_h['status_BMI'] == 'Overweight').sum()
jumlah_obesity = (df_h['status_BMI'] == 'Obesity').sum()

# Menampilkan hasil
print("Jumlah orang dengan status Underweight:", jumlah_underweight)
print("Jumlah orang dengan status Normal:", jumlah_normal)
print("Jumlah orang dengan status Overweight:", jumlah_overweight)
print("Jumlah orang dengan status Obesity:", jumlah_obesity)

Jumlah orang dengan status Underweight: 3
Jumlah orang dengan status Normal: 16
Jumlah orang dengan status Overweight: 3
Jumlah orang dengan status Obesity: 2